service: monolambda-backend

provider:
  name: aws
  runtime: nodejs6.10
  stage: production
  region: us-east-2
  iamRoleStatements:
  - Effect: Allow
    Action:
      - 'lambda:InvokeFunction'
    Resource:
      - 'Fn::Join':
          - ':'
          - - 'arn:aws:lambda'
            - Ref: 'AWS::Region'
            - Ref: 'AWS::AccountId'
            - 'function:${self:service}-${opt:stage, self:provider.stage}-*'

package:
  individually: true
  exclude:
    - .git/**
    - resources/**
    - README.md
    - LICENSE
    - .eslintrc
  
functions:
  contactForm:
    warmup: true
    description: Handles submitted contact forms on monolambda.com
    handler: src/functions/contactForm/contactForm.handleMessage
    memorySize: 256
    timeout: 3
    events:
      - http:
          path: contact-form
          method: POST
          cors: true

plugins:
  - serverless-plugin-warmup
custom:
  warmup:
    schedule: 'cron(*/10 * * * ? *)'
    prewarm: true