service: monolambda-backend

provider:
  name: aws
  runtime: nodejs6.10
  stage: production
  region: us-east-2

package:
  individually: true
  exclude:
    - .git/**
    - resources/**
    - README.md
    - LICENSE
    - .eslintrc
  
functions:
  contactForm:
    description: Handles submitted contact forms on monolambda.com
    handler: src/functions/contactForm/contactForm.handleMessage
    memorySize: 256
    timeout: 3
    events:
      - http:
          path: contact-form
          method: POST
          cors: true
  healthCheck:
    description: Handles health check for all other functions
    handler: src/functions/healthCheck/healthCheck.handleHealthCheck
    memorySize: 128
    timeout: 3
    events:
      - http:
          path: health-check
          method: GET
          cors: true